# Site settings
title: The site with paginated blog samplz
email: your-email@domain.com
description: "This is an example of a site with a paginated blog main page."
baseurl: ""
url: "http://yourdomain.com"
paginate: 2

# Build settings
markdown: kramdown
permalink: pretty
